using System.Collections;
using System.Net;
using System.Net.Sockets;
using System.Text;
using DHT;

var content = new KRPC().SendPing("909f9cbdedf4f7e29e820e3fd5e00a2965450b8a").ConvertToBEncode().ToString();
Console.WriteLine($"发送数据[{content}]");
var bytes = Encoding.ASCII.GetBytes(content);
var udpClient = new UdpClient(6881, AddressFamily.InterNetwork);
var endPoint = new IPEndPoint(IPAddress.Any, 0);
udpClient.Send(bytes, "87.98.162.88", 6881);
var bytes1 = udpClient.Receive(ref endPoint);
// var entry = Dns.GetHostEntry(Dns.GetHostName());
// var addr = entry.AddressList.First(a => a.ToString() == "172.20.10.2");
// var endPoint = new IPEndPoint(addr, 12345);
// var socket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
// socket.Bind(endPoint);
// var remoteEntry = Dns.GetHostEntry("dht.transmissionbt.com");
// var remoteAddr = remoteEntry.AddressList.First(a => a.AddressFamily == AddressFamily.InterNetwork);
// var remoteEndPoint = new IPEndPoint(remoteAddr, 6881);
// socket.SendTo(bytes, 0, bytes.Length, SocketFlags.None, remoteEndPoint);
// socket.Close();
// socket=new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
// socket.Bind(new IPEndPoint(addr, 12345));
// var bytes1 = new byte[256];
// var reE = (EndPoint)remoteEndPoint;
// socket.ReceiveFrom(bytes1, 0, bytes.Length, SocketFlags.None, ref reE);
var result = Encoding.ASCII.GetString(bytes1);
var resBe = new BEncode(result).Read();
var id = ((resBe[0] as IDictionary)?["r"] as IDictionary)?["id"];
// var hex = Utils.StringToHex((string)id);
// content = new KRPC().FindNode("909f9cbdedf4f7e29e820e3fd5e00a2965450b8a", "909f9cbdedf4f7e29e820e3fd5e00a2965450b8a").ConvertToBEncode().ToString();
// bytes = Encoding.ASCII.GetBytes(content);
// udpClient.Send(bytes, "87.98.162.88", 6881);
// bytes1 = udpClient.Receive(ref endPoint);
// result = Encoding.ASCII.GetString(bytes1);
// resBe = new BEncode(result).Read();

udpClient.Close();